#!/bin/bash
OUTPUT_FILE="db-password-fix.txt"

{
echo "========================================="
echo "Database Password Fix - $(date)"
echo "========================================="
echo ""

echo "ISSUE: Application is using wrong database password"
echo ""
echo "Current situation:"
echo "  - Database Host: 10.42.42.9"
echo "  - Database User: iqgeo"
echo "  - Current Password in ConfigMap: 6hPfVGmi9gMMhhmE5pR64xDz4ahcQnvg (Harbor password - WRONG!)"
echo ""
echo "========================================="
echo "REQUIRED: Provide the ACTUAL PostgreSQL database password"
echo "========================================="
echo ""
echo "Please check what password was configured on the PostgreSQL server at 10.42.42.9"
echo ""
echo "Options to find the password:"
echo ""
echo "1. Check the database server setup scripts/documentation"
echo "2. SSH to database server and check: sudo grep 'password' /var/log/postgresql/*.log"
echo "3. If you have database access, connect and check"
echo "4. Check any deployment notes or password management system"
echo ""
echo "Once you have the correct password, update it in TWO places:"
echo ""
echo "=== Place 1: Prerequisites terraform.tfvars (on server) ==="
echo "File: /opt/iqgeo-onprem-deployment/terraform/terraform.tfvars"
echo "Line 24: db_password = \"THE_ACTUAL_PASSWORD\""
echo ""
echo "=== Place 2: Application terraform.tfvars (on server) ==="
echo "File: /opt/iqgeo-application-deployment/terraform.tfvars"
echo "Line 31: db_password = \"THE_ACTUAL_PASSWORD\""
echo ""
echo "=== Then patch the ConfigMap ===" 
echo "Run this command with the ACTUAL password:"
echo ""
echo "kubectl patch configmap iqgeo-platform-configmap -n iqgeo --type merge -p '{"
echo "  \"data\": {"
echo "    \"MYW_DB_PASSWORD\": \"THE_ACTUAL_PASSWORD\","
echo "    \"PGPASSWORD\": \"THE_ACTUAL_PASSWORD\""
echo "  }"
echo "}'"
echo ""
echo "=== Restart the pod ==="
echo "kubectl delete pod -n iqgeo -l app=iqgeo-platform"
echo ""
echo "========================================="
echo ""
echo "ALTERNATIVE: If database user 'iqgeo' doesn't exist yet,"
echo "you may need to create it on the database server:"
echo ""
echo "On database server (10.42.42.9):"
echo "  sudo -u postgres psql"
echo "  CREATE USER iqgeo WITH PASSWORD 'YOUR_CHOSEN_PASSWORD';"
echo "  CREATE DATABASE iqgeo OWNER iqgeo;"
echo "  GRANT ALL PRIVILEGES ON DATABASE iqgeo TO iqgeo;"
echo "  \\q"
echo ""
echo "Then use YOUR_CHOSEN_PASSWORD in the steps above."
echo ""
echo "========================================="

} > "$OUTPUT_FILE" 2>&1

cat "$OUTPUT_FILE"
echo ""
echo "✅ Instructions saved to $OUTPUT_FILE"
